name: 'Merge JSONs Action'
description: 'GCombine multiple json files in a dir into one'
inputs:
  caminho:
    description: 'Caminho dos arquivos'
    required: true
    default: '/'
  prefixo:
    description: 'Prefixo dos arquivos a serem combinados'
    required: true
    default: 'BS'
outputs:
  consolidado:
    description: 'Arquivo consolidado'
  resumo:
    description: 'Nomes dos modelos de acordo com o código'
runs:
  using: 'node20'
  main: 'dist/index.js'
