name: 'Merge JSONs Action'
description: 'GCombine multiple json files in a dir into one'
inputs:
  prefixo:
    description: 'Prefixo dos arquivos a serem combinados'
    required: true
    default: 'BS'
outputs:
  consolidado:
    description: 'Arquivo consolidado'
runs:
  using: 'node20'
  main: 'dist/index.js'
